spring.application.name=notificacao

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/notificacao
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8088/eureka/

# =========================
# Kafka
# =========================

spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094

# =========================
# Producer
# =========================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Não enviar o nome da classe Java no header
spring.kafka.producer.properties.spring.json.add.type.headers=false

# =========================
# Consumer
# =========================

spring.kafka.consumer.group-id=notificacao
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# =========================
# Topics
# =========================

topics.lista-entregadores=lista-entregadores
topics.pedido-aceito=pedido-aceito