spring.application.name=logistica

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.maps.api-key=AIzaSyCZwNPn0wKMHqqJrWgjWDnopumkMpQmyxk

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8088/eureka/


spring.kafka.bootstrap-servers=localhost:9092,localhost:9093

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=logistica
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


topics.endereco-cadastrado=endereco-cadastrado

topics.endereco-localizado=endereco-localizado

topics.pedido-criado=pedido-criado

topics.lista-entregadores=lista-entregadores

graylog.host=localhost
graylog.port=12201