apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: ecommerce
spec:
  clusterIP: None
  selector:
    app: kafka-1
  ports:
    - name: internal
      port: 19092
      targetPort: 19092
    - name: controller
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: ecommerce
spec:
  clusterIP: None
  selector:
    app: kafka-2
  ports:
    - name: internal
      port: 19092
      targetPort: 19092
    - name: controller
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1
  namespace: ecommerce
spec:
  serviceName: kafka-1
  replicas: 1

  selector:
    matchLabels:
      app: kafka-1

  template:
    metadata:
      labels:
        app: kafka-1

    spec:
      containers:
        - name: kafka
          image: apache/kafka:4.3.1

          ports:
            - containerPort: 19092
            - containerPort: 29092
            - containerPort: 9092

          env:
            - name: KAFKA_NODE_ID
              value: "1"

            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

            - name: KAFKA_LISTENERS
              value: "INTERNAL://:19092,CONTROLLER://:29092,EXTERNAL://:9092"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-1:19092,EXTERNAL://localhost:9092"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-1:29092,2@kafka-2:29092"

            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"

            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"

            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-2
  namespace: ecommerce
spec:
  serviceName: kafka-2
  replicas: 1

  selector:
    matchLabels:
      app: kafka-2

  template:
    metadata:
      labels:
        app: kafka-2

    spec:
      containers:
        - name: kafka
          image: apache/kafka:4.3.1

          ports:
            - containerPort: 19092
            - containerPort: 29092
            - containerPort: 9092

          env:
            - name: KAFKA_NODE_ID
              value: "2"

            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

            - name: KAFKA_LISTENERS
              value: "INTERNAL://:19092,CONTROLLER://:29092,EXTERNAL://:9092"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-2:19092,EXTERNAL://localhost:9093"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-1:29092,2@kafka-2:29092"

            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"

            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "2"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"

            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 10Gi