apiVersion: v1
kind: ConfigMap
metadata:
  name: banco-init
  namespace: ecommerce
data:
  banco.sql: |
    CREATE DATABASE empresa;
    CREATE DATABASE entregador;
    CREATE DATABASE estoque;
    CREATE DATABASE logistica;
    CREATE DATABASE notificacao;
    CREATE DATABASE pedidos;
    CREATE DATABASE produtos;
    CREATE DATABASE usuario;

    \connect empresa
    CREATE EXTENSION IF NOT EXISTS postgis;

    \connect entregador
    CREATE EXTENSION IF NOT EXISTS postgis;

    \connect logistica
    CREATE EXTENSION IF NOT EXISTS postgis;

    \connect usuario
    CREATE EXTENSION IF NOT EXISTS postgis;

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce
spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ecommerce
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: "postgres"

            - name: POSTGRES_PASSWORD
              value: "1234"

            - name: POSTGRES_DB
              value: "postgres"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: banco-init
              mountPath: /docker-entrypoint-initdb.d/banco.sql
              subPath: banco.sql

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 20

      volumes:
        - name: banco-init
          configMap:
            name: banco-init

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 20Gi