spring.application.name=pedidos

server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8088/eureka/

spring.kafka.bootstrap-servers=localhost:9092,localhost:9093

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

topics.pedido-criado=pedido-criado
topics.pedido-aceito=pedido-aceito

graylog.host=localhost
graylog.port=12201
