spring.application.name=server

server.port=8088
eureka.instance.hostname=localhost


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

graylog.host=localhost
graylog.port=12201